"""Export simulated band financials for the BandPeace demo site.

Runs a 36-month bandsim simulation (SimClock start 2026-01-01, seed 42 —
same pattern as bandsim/cli.py run()) and emits:

  site/data.json                       — monthly income rows by bucket,
                                         monthly expense totals, per-year
                                         Schedule C summaries
  site/files/schedule_c_<year>_SIMULATED.txt  (2026, 2027, 2028)
  site/files/pnl_2026.xlsx             — copied from band-biz-sim/out/
  site/files/royalty_map_2026.csv      — copied from band-biz-sim/out/

Everything is SIMULATED — seed-fiction dollars, fake band, fake EIN.

Run with the sim's venv:
  /Users/edwardmcgowen/projects/band-biz-sim/.venv/bin/python scripts/export_data.py

Exits nonzero if the exported buckets do not reconcile, to the penny, with
the QuickHooks ledger totals the sim itself reports.
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import date, timedelta
from pathlib import Path

BANDSIM_ROOT = Path("/Users/edwardmcgowen/projects/band-biz-sim")
sys.path.insert(0, str(BANDSIM_ROOT))

from bandsim.clock import SimClock                          # noqa: E402
from bandsim.hub.categories import SCHEDULE_C_MAP           # noqa: E402
from bandsim.hub.quickhooks import QuickHooks               # noqa: E402
from bandsim.money.banks import BankAccount, Transaction    # noqa: E402
from bandsim.money.expenses import simulate_expenses        # noqa: E402
from bandsim.money.payment_apps import PaymentApp, simulate_app_activity  # noqa: E402
from bandsim.streams.base import Song                       # noqa: E402
from bandsim.streams.rights_engine import RightsEngine      # noqa: E402
from bandsim.tax.schedule_c import SE_NET_MULTIPLIER, SE_TAX_RATE, build_filing  # noqa: E402

SITE = Path(__file__).resolve().parent.parent / "site"
FILES = SITE / "files"

MONTHS = 36
SEED = 42
YEARS = [2026, 2027, 2028]

# Demo band catalog (fictional — mirrors the sim's default shape)
CATALOG = [
    Song("Traffic Cone Anthem", 3.0),
    Song("In Deh", 1.8),
    Song("Number Nine (Remix)", 1.4),
    Song("Barn Sound Bath", 0.6),
    Song("Rooftop First Light", 0.3),
]

# The site's filterable buckets, in display order.
BUCKETS = [
    "Streaming royalties",
    "Publishing",
    "Sync licensing",
    "Other royalties",
    "Live shows",
    "Merch — online",
    "Merch — in person",
    "Other income",
]

DISTRIBUTOR_STREAMS = {"DistroKid", "Symphonic"}          # recording-side distributor lane
PUBLISHING_STREAMS = {"ASCAP-sim", "Songtrust-sim", "HFA-sim"}  # composition-side collectors
OTHER_ROYALTY_STREAMS = {"SoundExchange-sim", "Direct-to-band"}

DISCLAIMER = (
    "SIMULATION — NOT TAX ADVICE, NOT A REAL FILING.\n"
    "Generated by bandsim from random-seed fiction for the BandPeace demo.\n"
    "EIN 00-0000000 is deliberately invalid. The band is fictional.\n"
)


def bucket_statement(st) -> dict[str, float]:
    """Split one statement's NET payout across the site buckets, to the penny.

    Sync-related lines (source contains 'sync') are pulled into 'Sync licensing'
    regardless of which collector mailed the statement; the collector's fee is
    prorated across lines; any rounding residual lands on the largest bucket so
    the bucket sum always equals st.net_payout exactly.
    """
    gross = st.gross
    net = st.net_payout
    if gross == 0:
        return {}

    def bucket_for(line) -> str:
        if "sync" in line.source:
            return "Sync licensing"
        if st.stream_name in DISTRIBUTOR_STREAMS:
            return "Streaming royalties"
        if st.stream_name in PUBLISHING_STREAMS:
            return "Publishing"
        if st.stream_name in OTHER_ROYALTY_STREAMS:
            return "Other royalties"
        return "Other royalties"

    raw: dict[str, float] = {}
    for line in st.lines:
        raw[bucket_for(line)] = raw.get(bucket_for(line), 0.0) + line.amount

    scale = net / gross  # prorate the collector's fee across lines
    out = {b: round(v * scale, 2) for b, v in raw.items()}
    residual = round(net - sum(out.values()), 2)
    if residual:
        biggest = max(out, key=out.get)
        out[biggest] = round(out[biggest] + residual, 2)
    return out


def run_sim():
    """36-month run, same wiring as bandsim.cli.run()."""
    clock = SimClock(start=date(2026, 1, 1), months=MONTHS, seed=SEED)
    checking = BankAccount("SimBank Business Checking", "SIM-CHK-FAKE", "checking")
    credit = BankAccount("SimBank Visa", "SIM-CC-FAKE", "credit", opening_balance=0.0)
    apps = {
        "venmo": PaymentApp("SimVenmo", "venmo"),
        "paypal": PaymentApp("SimPayPal", "paypal"),
        "zelle": PaymentApp("SimZelle", "zelle"),
    }
    engine = RightsEngine(CATALOG)

    for month_start in clock.month_starts():
        engine.simulate_month(clock, month_start)
        simulate_expenses(clock, month_start, checking, credit)
        simulate_app_activity(clock, month_start, apps, checking)

    # land royalty payouts through the end of the simulated window (cash basis)
    horizon = date(YEARS[-1], 12, 31)
    landed = []
    for st in engine.statements:
        if st.payout_date <= horizon:
            checking.post(Transaction(
                date=st.payout_date,
                description=f"{st.stream_name} royalties {st.period_start:%b %Y}",
                amount=st.net_payout, account=checking.name, channel="bank",
                category_hint="Music Royalties",
            ))
            landed.append(st)

    hub = QuickHooks()
    hub.ingest_accounts([checking, credit])
    hub.ingest_apps(list(apps.values()))
    return clock, hub, landed, engine


def avg_monthly_streams(statements) -> int:
    """Average monthly streams across the whole run, straight from the
    distributor statements (store lines only — the appended 'download ·' /
    'video ·' rights lines are not streams)."""
    units = sum(
        line.units
        for st in statements
        if st.stream_name in DISTRIBUTOR_STREAMS
        for line in st.lines
        if "·" not in line.source
    )
    return round(units / MONTHS)


def schedule_c_summary(hub: QuickHooks, year: int) -> dict:
    """Recompute of bandsim.tax.schedule_c.build_filing math.

    DUPLICATION WARNING: this mirrors the math inside
    bandsim/tax/schedule_c.py::build_filing (which computes and writes its txt
    in one function, so the math cannot be imported alone without refactoring
    bandsim). To keep the two from silently diverging, main() ALSO runs the
    real build_filing and cross-checks the numbers parsed from its output
    against this recompute — any mismatch fails the export (see
    cross_check_schedule_c below)."""
    gross = hub.business_income(year)
    cat_totals = hub.totals_by_category(year)
    lines: dict[str, tuple[str, float]] = {}
    for category, (line_no, label) in SCHEDULE_C_MAP.items():
        amount = -cat_totals.get(category, 0.0)
        if amount <= 0:
            continue
        if category == "Meals":
            amount *= 0.5
        prev = lines.get(line_no, (label, 0.0))[1]
        lines[line_no] = (label, round(prev + amount, 2))
    total_deductions = round(sum(v for _, v in lines.values()), 2)
    net_profit = round(gross - total_deductions, 2)
    se_base = round(max(0.0, net_profit) * SE_NET_MULTIPLIER, 2)
    se_tax = round(se_base * SE_TAX_RATE, 2)
    return {
        "year": year,
        "gross_receipts": gross,
        "total_deductions": total_deductions,
        "net_profit": net_profit,
        "se_tax": se_tax,
        "lines": {no: {"label": lab, "amount": amt} for no, (lab, amt) in
                  sorted(lines.items(), key=lambda x: (len(x[0]), x[0]))},
    }


def cross_check_schedule_c(hub: QuickHooks, summary: dict, scratch: Path) -> bool:
    """Run the REAL bandsim build_filing and verify our recompute matches it.

    This is the guard against the duplication documented on
    schedule_c_summary: gross, total deductions, net profit and SE tax are
    parsed from build_filing's own output and compared to the penny."""
    import re
    year = summary["year"]
    txt = build_filing(hub, year, scratch).read_text()

    def grab(pattern: str) -> float:
        m = re.search(pattern + r"\.*\s*\$\s*([\d,]+\.\d{2})", txt)
        return float(m.group(1).replace(",", "")) if m else float("nan")

    pairs = [
        ("gross_receipts", grab(r"Line 1  Gross receipts")),
        ("total_deductions", grab(r"Line 28 Total expenses")),
        ("net_profit", grab(r"Line 31 NET PROFIT \(or loss\)")),
        ("se_tax", grab(r"SE tax \(x [\d.]+\)")),
    ]
    ok = True
    for key, theirs in pairs:
        if abs(summary[key] - theirs) > 0.005:
            ok = False
            print(f"  SCHEDULE C CROSS-CHECK MISMATCH {year} {key}: "
                  f"recompute {summary[key]} vs build_filing {theirs}")
    return ok


def write_schedule_c_txt(summary: dict, path: Path) -> None:
    year = summary["year"]
    with open(path, "w") as f:
        f.write(DISCLAIMER + "\n")
        f.write(f"SCHEDULE C (Form 1040) — Profit or Loss From Business — TY {year}\n")
        f.write("Proprietor: Fly Asshole LLC (FICTIONAL DEMO BAND)   EIN: 00-0000000\n")
        f.write("Principal business: Musician / performing artist (NAICS 711130)\n")
        f.write("=" * 64 + "\n\n")
        f.write("PART I — INCOME\n")
        f.write(f"  Line 1  Gross receipts.......................... ${summary['gross_receipts']:>12,.2f}\n")
        f.write(f"  Line 7  Gross income............................ ${summary['gross_receipts']:>12,.2f}\n\n")
        f.write("PART II — EXPENSES\n")
        for line_no, d in summary["lines"].items():
            f.write(f"  Line {line_no:<4}{d['label']:.<38} ${d['amount']:>12,.2f}\n")
        f.write(f"  Line 28 Total expenses.......................... ${summary['total_deductions']:>12,.2f}\n\n")
        f.write(f"  Line 31 NET PROFIT (or loss).................... ${summary['net_profit']:>12,.2f}\n\n")
        f.write("SCHEDULE SE (shape) — Self-Employment Tax\n")
        se_base = round(max(0.0, summary["net_profit"]) * SE_NET_MULTIPLIER, 2)
        f.write(f"  Net earnings from SE (x {SE_NET_MULTIPLIER})............ ${se_base:>12,.2f}\n")
        f.write(f"  SE tax (x {SE_TAX_RATE})............................ ${summary['se_tax']:>12,.2f}\n\n")
        f.write(DISCLAIMER)


def main() -> int:
    clock, hub, landed, engine = run_sim()

    # ── income rows by bucket ────────────────────────────────────────────
    # (year, month, bucket) -> amount
    rows: dict[tuple[int, int, str], float] = {}

    def add(y: int, m: int, bucket: str, amount: float) -> None:
        key = (y, m, bucket)
        rows[key] = round(rows.get(key, 0.0) + amount, 2)

    # royalty statements → royalty buckets, on their payout (cash) month
    for st in landed:
        for bucket, amount in bucket_statement(st).items():
            add(st.payout_date.year, st.payout_date.month, bucket, amount)

    # non-royalty income straight from the ledger
    for e in hub.entries:
        if e.kind != "income" or e.date.year not in YEARS:
            continue
        if e.category == "Music Royalties":
            continue  # already covered by statements above
        if e.category.startswith("Performance"):
            b = "Live shows"
        elif e.category == "Merch Sales":
            b = "Merch — online" if e.channel == "paypal" else "Merch — in person"
        else:
            b = "Other income"
        add(e.date.year, e.date.month, b, e.amount)

    # monthly expense totals
    expenses = [
        {"year": y, "month": m, "amount": hub.business_expenses(y, m)}
        for y in YEARS for m in range(1, 13)
    ]

    # ── reconciliation ───────────────────────────────────────────────────
    print("bandpeace export — reconciliation (seed", SEED, ",", MONTHS, "months)")
    ok = True
    royalty_buckets = {"Streaming royalties", "Publishing", "Sync licensing", "Other royalties"}
    for y in YEARS:
        bucket_income = round(sum(v for (yy, _, _), v in rows.items() if yy == y), 2)
        bucket_royalties = round(sum(v for (yy, _, b), v in rows.items()
                                     if yy == y and b in royalty_buckets), 2)
        ledger_income = hub.business_income(y)
        ledger_royalties = round(hub.totals_by_category(y).get("Music Royalties", 0.0), 2)
        ledger_expenses = hub.business_expenses(y)
        inc_ok = bucket_income == ledger_income
        roy_ok = bucket_royalties == ledger_royalties
        ok = ok and inc_ok and roy_ok
        print(f"  {y}: income buckets ${bucket_income:>10,.2f} vs ledger ${ledger_income:>10,.2f} "
              f"[{'OK' if inc_ok else 'MISMATCH'}]")
        print(f"        royalty buckets ${bucket_royalties:>10,.2f} vs ledger 'Music Royalties' "
              f"${ledger_royalties:>10,.2f} [{'OK' if roy_ok else 'MISMATCH'}]")
        print(f"        expenses ${ledger_expenses:>10,.2f}   net ${ledger_income - ledger_expenses:>10,.2f}")

    # monthly-level royalty check too (payout-month attribution must match ledger)
    for y in YEARS:
        for m in range(1, 13):
            bucket_m = round(sum(v for (yy, mm, b), v in rows.items()
                                 if yy == y and mm == m and b in royalty_buckets), 2)
            ledger_m = round(hub.totals_by_category(y, m).get("Music Royalties", 0.0), 2)
            if bucket_m != ledger_m:
                ok = False
                print(f"  MONTHLY MISMATCH {y}-{m:02d}: buckets ${bucket_m} vs ledger ${ledger_m}")

    if not ok:
        print("RECONCILIATION FAILED — data.json NOT written.")
        return 1
    print("  monthly royalty attribution: OK, all 36 months to the penny")

    # ── schedule C summaries + txt files ─────────────────────────────────
    FILES.mkdir(parents=True, exist_ok=True)
    scratch = Path(__file__).resolve().parent / ".schedule_c_crosscheck"
    scratch.mkdir(exist_ok=True)
    schedules = {}
    for y in YEARS:
        s = schedule_c_summary(hub, y)
        if not cross_check_schedule_c(hub, s, scratch):
            print("SCHEDULE C CROSS-CHECK FAILED — data.json NOT written.")
            return 1
        schedules[str(y)] = s
        write_schedule_c_txt(s, FILES / f"schedule_c_{y}_SIMULATED.txt")
        print(f"  Schedule C {y}: gross ${s['gross_receipts']:,.2f}  deductions "
              f"${s['total_deductions']:,.2f}  net ${s['net_profit']:,.2f}  SE tax ${s['se_tax']:,.2f}"
              f"  [matches bandsim build_filing]")
    shutil.rmtree(scratch, ignore_errors=True)

    streams_avg = avg_monthly_streams(engine.statements)
    print(f"  avg monthly streams (distributor store lines / {MONTHS} months): {streams_avg:,}")

    # ── copy artifacts from the sim's out/ dir ───────────────────────────
    for name in ("pnl_2026.xlsx", "royalty_map_2026.csv"):
        src = BANDSIM_ROOT / "out" / name
        if src.exists():
            shutil.copy2(src, FILES / name)
        else:
            print(f"  WARNING: {src} missing — run the sim's CLI first")

    # ── data.json ────────────────────────────────────────────────────────
    data = {
        "meta": {
            "generated": date.today().isoformat(),
            "seed": SEED,
            "months": MONTHS,
            "years": YEARS,
            "simulated": True,
            "avg_monthly_streams": streams_avg,
            "note": "All figures are simulated fiction generated by bandsim. Fictional demo band.",
        },
        "categories": BUCKETS,
        "monthly": [
            {"year": y, "month": m, "category": b, "amount": v}
            for (y, m, b), v in sorted(rows.items(), key=lambda kv: (kv[0][0], kv[0][1], BUCKETS.index(kv[0][2])))
            if v != 0
        ],
        "expenses": expenses,
        "schedule_c": schedules,
    }
    out_path = SITE / "data.json"
    with open(out_path, "w") as f:
        json.dump(data, f, indent=1)
    print(f"  wrote {out_path} ({out_path.stat().st_size:,} bytes, "
          f"{len(data['monthly'])} monthly rows)")
    print("RECONCILIATION OK — export complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
